apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "matomo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "matomo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.matomo.runAsUser }}
        fsGroup: {{ .Values.matomo.fsGroup }}      
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_HOST
              value: {{ .Values.matomo.mariadbHost }}   
            - name: MARIADB_PORT_NUMBER
              value: {{ .Values.matomo.mariadbPortNumber }}     
            - name: MATOMO_DATABASE_USER
              value: {{ .Values.matomo.matomoDatabaseUser }}   
            - name: MATOMO_DATABASE_NAME
              value: {{ .Values.matomo.matomoDatabaseName }}
            - name: ALLOW_EMPTY_PASSWORD
              value: {{ .Values.matomo.allowEmptyPassword }}
            - name: MATOMO_EMAIL
              value: {{ .Values.matomo.matomoEmail }}
            - name: MATOMO_PASSWORD
              value: {{ .Values.matomo.matomoPassword }}
          ports:
            - containerPort: {{ .Values.service.portHttp }}
              name: {{ .Values.service.portNameHttp }}
            - containerPort: {{ .Values.service.portHttps }}
              name: {{ .Values.service.portNameHttps }}                        
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}