apiVersion: v1
kind: Service
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHttp }}
      targetPort: {{ .Values.service.targetPortHttp }}
      protocol: TCP
      name: {{ .Values.service.portNameHttp }}
    - port: {{ .Values.service.portHttps }}
      targetPort: {{ .Values.service.targetPortHttps }}
      protocol: TCP
      name: {{ .Values.service.portNameHttps }}      
  selector:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
