apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb.name" . }}
    helm.sh/chart: {{ include "mariadb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "mariadb.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mariadb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mariadb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.mariadb.runAsUser }}
        fsGroup: {{ .Values.mariadb.fsGroup }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_USER
              value: {{ .Values.mariadb.mariadbUser }}   
            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.mariadbDatabase }}     
            - name: ALLOW_EMPTY_PASSWORD
              value: {{ .Values.mariadb.allowEmptyPassword }}   
            - name: MARIADB_EXTRA_FLAGS
              value: {{ .Values.mariadb.mariadbExtraFlags }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ .Values.service.portName }}  
          volumeMounts:
            - name: {{ .Values.persistence.name }}
              mountPath: /var/lib/mysql              
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.name }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.persistence.size }}"
