replicaCount: 1

image:
  repository: bitnami/mariadb
  tag: 10.3-debian-10
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

mariadb:
  mariadbUser: SHOULD_BE_REPLACED_BY_DEPLOYMENT_TOOL
  mariadbDatabase: SHOULD_BE_REPLACED_BY_DEPLOYMENT_TOOL
  allowEmptyPassword: "'yes'"
  mariadbExtraFlags: "--max_allowed_packet=64MB"
  runAsUser: 1001
  fsGroup: 1001

service:
  type: ClusterIP
  port: 3306
  portName: mariadb
  targetPort: 3306  

resources:
   limits:
     cpu: 500m
     memory: 256Mi
   requests:
     memory: 128Mi
     cpu: 1m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  name: mariadb-data
  size: "1Gi"
  
nodeSelector: {}

tolerations: []

affinity: {}