version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.3-debian-10
    container_name: mariadb
    environment:
      - MARIADB_USER=matomo
      - MARIADB_DATABASE=matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - 'mariadb_data:/mariadb'

  matomo:
    image: bitnami/matomo:4-debian-10
    container_name: matomo
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_PORT_NUMBER=matomo
      - MATOMO_DATABASE_NAME=matomo
      - MATOMO_DATABASE_USER=matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MATOMO_USERNAME=marcel.schmitt@schmittformatik.de
      - MATOMO_PASSWORD=test123
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local